info:
  title: Example API
  version: '1.0'
openapi: 3.0.0
paths:
  /api/statistics:
    get:
      responses:
        200:
          description: Tweets statistics - most popular hashtags, top users who made
            max amount of tweets, total tweets count
          examples:
            phrase: bom bom
            top_hashtags:
            - count: 5
              tag: bom
            - count: 2
              tag: secondbom
            - count: 1
              tag: thirdbom
            top_users:
            - count: 5
              id: 93787352
              screen_name: bombom_pro
            - count: 3
              id: 1149722107
              screen_name: xXxBomBomxXx
            - count: 1
              id: 2632353897
              screen_name: bombom98
            tweets_count: 10
  /api/tweets:
    get:
      responses:
        200:
          description: A list of users.
          examples:
          - hashtags:
            - bom
            - secondbom
            id: 1182368240686784512
            published_at: Thu Oct 10 18:52:10 2019
            text: 'Bom bom bom #bom #secondbom'
            user_id: 93787352
