version: '3'
services:
  web:
    build: .
    ports:
      - '5000:5000'
    depends_on:
      - postgres
      - redis
  
  postgres:
    container_name: 'postgres'
    image: 'postgres:12'
    env_file: '.env'
    ports:
      - '5432:5432'
    volumes:
      - 'pgdata:/var/lib/postgresql/data/'
  
  redis:
    container_name: 'redis'
    image: 'redis:alpine'
    env_file: '.env'
    ports:
      - '6379:6379'

volumes:
  pgdata: